In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

# Date

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

## Now change the Datatype

In [7]:
date['date']=pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

# 1 Extract Year

In [9]:
date['date_year']=date['date'].dt.year

In [10]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

# 2 Extract Month

In [11]:
date['date_month']=date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

## 2.1 Extract Month in english

In [13]:
date['date_month_name']=date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name
0,2019-12-10,5628,25,3,2019,12,date,December
1,2018-08-15,3646,14,157,2018,8,date,August
2,2018-10-23,1859,25,1,2018,10,date,October
3,2019-08-17,7292,25,1,2019,8,date,August
4,2019-01-06,4344,25,3,2019,1,date,January

# 3 Extract DAy

In [12]:
date['date_day']=date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year  date_month date_day
0 2019-12-10        5628       25       3       2019          12     date
1 2018-08-15        3646       14     157       2018           8     date
2 2018-10-23        1859       25       1       2018          10     date
3 2019-08-17        7292       25       1       2019           8     date
4 2019-01-06        4344       25       3       2019           1     date

## 3.1 Extract Day name in english

In [15]:
date['date_day_name']=date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_day_name
0,2019-12-10,5628,25,3,2019,12,date,December,Tuesday
1,2018-08-15,3646,14,157,2018,8,date,August,Wednesday
2,2018-10-23,1859,25,1,2018,10,date,October,Tuesday
3,2019-08-17,7292,25,1,2019,8,date,August,Saturday
4,2019-01-06,4344,25,3,2019,1,date,January,Sunday

In [16]:
date.drop(columns=['product_id','city_id','orders'],inplace=True)

In [17]:
date.head()

        date  date_year  date_month date_day date_month_name date_day_name
0 2019-12-10       2019          12     date        December       Tuesday
1 2018-08-15       2018           8     date          August     Wednesday
2 2018-10-23       2018          10     date         October       Tuesday
3 2019-08-17       2019           8     date          August      Saturday
4 2019-01-06       2019           1     date         January        Sunday

## 3.2 day of Week

In [18]:
date['date_day_of_week']=date['date'].dt.dayofweek
date.head()

,date,date_year,date_month,date_day,date_month_name,date_day_name,date_day_of_week
0,2019-12-10,2019,12,date,December,Tuesday,1
1,2018-08-15,2018,8,date,August,Wednesday,2
2,2018-10-23,2018,10,date,October,Tuesday,1
3,2019-08-17,2019,8,date,August,Saturday,5
4,2019-01-06,2019,1,date,January,Sunday,6

# 4 WeekEnd

In [19]:
date['date_WeekEnd']=np.where(date['date_day_name'].isin(['Saturday','Sunday']),1,0)
date.head()

,date,date_year,date_month,date_day,date_month_name,date_day_name,date_day_of_week,date_WeekEnd
0,2019-12-10,2019,12,date,December,Tuesday,1,0
1,2018-08-15,2018,8,date,August,Wednesday,2,0
2,2018-10-23,2018,10,date,October,Tuesday,1,0
3,2019-08-17,2019,8,date,August,Saturday,5,1
4,2019-01-06,2019,1,date,January,Sunday,6,1

# 5 Exract Week of the Year

In [23]:
date['date_week'] = date['date'].dt.isocalendar().week
date.head()

,date,date_year,date_month,date_day,date_month_name,date_day_name,date_day_of_week,date_WeekEnd,date_week
0,2019-12-10,2019,12,date,December,Tuesday,1,0,50
1,2018-08-15,2018,8,date,August,Wednesday,2,0,33
2,2018-10-23,2018,10,date,October,Tuesday,1,0,43
3,2019-08-17,2019,8,date,August,Saturday,5,1,33
4,2019-01-06,2019,1,date,January,Sunday,6,1,1

# 6 Extract Quarter

In [24]:
date['quarter'] = date['date'].dt.quarter
date.head()

,date,date_year,date_month,date_day,date_month_name,date_day_name,date_day_of_week,date_WeekEnd,date_week,quarter
0,2019-12-10,2019,12,date,December,Tuesday,1,0,50,4
1,2018-08-15,2018,8,date,August,Wednesday,2,0,33,3
2,2018-10-23,2018,10,date,October,Tuesday,1,0,43,4
3,2019-08-17,2019,8,date,August,Saturday,5,1,33,3
4,2019-01-06,2019,1,date,January,Sunday,6,1,1,1